spring.datasource.url=jdbc:mysql://localhost:3306/narucivanje_knjiga_njt?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Krokodil03!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.property-naming-strategy=SNAKE_CASE
# detaljne poruke o gre\u0161kama u response-u (dev)
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
cors.allowed-origins=http://localhost:3000,http://172.20.10.3:3000